#############################################################################
# Makefile for building: 8sem
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 3 22:58:11 2018
# Project:  8sem.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile 8sem.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c \
		prints.c \
		norms.c \
		setka.c \
		functions.c \
		laspack/eigenval.c \
		laspack/errhandl.c \
		laspack/factor.c \
		laspack/itersolv.c \
		laspack/matrix.c \
		laspack/mlsolv.c \
		laspack/operats.c \
		laspack/precond.c \
		laspack/qmatrix.c \
		laspack/rtc.c \
		laspack/vector.c \
		shema.c \
		solver.c \
		gnuplot.c 
OBJECTS       = main.o \
		prints.o \
		norms.o \
		setka.o \
		functions.o \
		eigenval.o \
		errhandl.o \
		factor.o \
		itersolv.o \
		matrix.o \
		mlsolv.o \
		operats.o \
		precond.o \
		qmatrix.o \
		rtc.o \
		vector.o \
		shema.o \
		solver.o \
		gnuplot.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		8sem.pro
QMAKE_TARGET  = 8sem
DESTDIR       = 
TARGET        = 8sem

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 8sem.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile 8sem.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile 8sem.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/8sem1.0.0 || $(MKDIR) .tmp/8sem1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/8sem1.0.0/ && (cd `dirname .tmp/8sem1.0.0` && $(TAR) 8sem1.0.0.tar 8sem1.0.0 && $(COMPRESS) 8sem1.0.0.tar) && $(MOVE) `dirname .tmp/8sem1.0.0`/8sem1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/8sem1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

prints.o: prints.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o prints.o prints.c

norms.o: norms.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o norms.o norms.c

setka.o: setka.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setka.o setka.c

functions.o: functions.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o functions.o functions.c

eigenval.o: laspack/eigenval.c laspack/eigenval.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/precond.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h \
		laspack/rtc.h \
		laspack/itersolv.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o eigenval.o laspack/eigenval.c

errhandl.o: laspack/errhandl.c laspack/errhandl.h \
		laspack/copyrght.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o errhandl.o laspack/errhandl.c

factor.o: laspack/factor.c laspack/factor.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o factor.o laspack/factor.c

itersolv.o: laspack/itersolv.c laspack/itersolv.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o itersolv.o laspack/itersolv.c

matrix.o: laspack/matrix.c laspack/matrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o matrix.o laspack/matrix.c

mlsolv.o: laspack/mlsolv.c laspack/mlsolv.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/matrix.h \
		laspack/qmatrix.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mlsolv.o laspack/mlsolv.c

operats.o: laspack/operats.c laspack/operats.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/vector.h \
		laspack/elcmp.h \
		laspack/matrix.h \
		laspack/qmatrix.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o operats.o laspack/operats.c

precond.o: laspack/precond.c laspack/precond.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/vector.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h \
		laspack/factor.h \
		laspack/itersolv.h \
		laspack/eigenval.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o precond.o laspack/precond.c

qmatrix.o: laspack/qmatrix.c laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o qmatrix.o laspack/qmatrix.c

rtc.o: laspack/rtc.c laspack/rtc.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/vector.h \
		laspack/elcmp.h \
		laspack/itersolv.h \
		laspack/qmatrix.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rtc.o laspack/rtc.c

vector.o: laspack/vector.c laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vector.o laspack/vector.c

shema.o: shema.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h \
		include/perem.c \
		include/viraj.c \
		include/nachal.c \
		include/mum.c \
		include/nodeparam.c \
		include/case0_L.c \
		include/case1_L.c \
		include/case2_L.c \
		include/case3_L.c \
		include/case4_L.c \
		include/case5_L.c \
		include/case6_L.c \
		include/case7_L.c \
		include/case0.c \
		include/case1.c \
		include/case2.c \
		include/case3.c \
		include/case4.c \
		include/case5.c \
		include/case6.c \
		include/case7.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o shema.o shema.c

solver.o: solver.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o solver.o solver.c

gnuplot.o: gnuplot.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gnuplot.o gnuplot.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

