#############################################################################
# Makefile for building: 8sem
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  8sem.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile 8sem.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 8sem1.0.0
DISTDIR = /home/yana/8sem/.tmp/8sem1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c \
		prints.c \
		norms.c \
		setka.c \
		functions.c \
		laspack/eigenval.c \
		laspack/errhandl.c \
		laspack/factor.c \
		laspack/itersolv.c \
		laspack/matrix.c \
		laspack/mlsolv.c \
		laspack/operats.c \
		laspack/precond.c \
		laspack/qmatrix.c \
		laspack/rtc.c \
		laspack/vector.c \
		shema.c \
		solver.c \
		gnuplot.c \
		shema_s.c \
		setka_s.c 
OBJECTS       = main.o \
		prints.o \
		norms.o \
		setka.o \
		functions.o \
		eigenval.o \
		errhandl.o \
		factor.o \
		itersolv.o \
		matrix.o \
		mlsolv.o \
		operats.o \
		precond.o \
		qmatrix.o \
		rtc.o \
		vector.o \
		shema.o \
		solver.o \
		gnuplot.o \
		shema_s.o \
		setka_s.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		8sem.pro head.h \
		structs.h \
		laspack/copyrght.h \
		laspack/eigenval.h \
		laspack/elcmp.h \
		laspack/errhandl.h \
		laspack/factor.h \
		laspack/itersolv.h \
		laspack/lastypes.h \
		laspack/matrix.h \
		laspack/mlsolv.h \
		laspack/operats.h \
		laspack/precond.h \
		laspack/qmatrix.h \
		laspack/rtc.h \
		laspack/vector.h \
		laspack/version.h main.c \
		prints.c \
		norms.c \
		setka.c \
		functions.c \
		laspack/eigenval.c \
		laspack/errhandl.c \
		laspack/factor.c \
		laspack/itersolv.c \
		laspack/matrix.c \
		laspack/mlsolv.c \
		laspack/operats.c \
		laspack/precond.c \
		laspack/qmatrix.c \
		laspack/rtc.c \
		laspack/vector.c \
		shema.c \
		solver.c \
		gnuplot.c \
		shema_s.c \
		setka_s.c
QMAKE_TARGET  = 8sem
DESTDIR       = 
TARGET        = 8sem


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 8sem.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		8sem.pro
	$(QMAKE) -o Makefile 8sem.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
8sem.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile 8sem.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

prints.o: prints.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o prints.o prints.c

norms.o: norms.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o norms.o norms.c

setka.o: setka.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setka.o setka.c

functions.o: functions.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o functions.o functions.c

eigenval.o: laspack/eigenval.c laspack/eigenval.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/precond.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h \
		laspack/rtc.h \
		laspack/itersolv.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o eigenval.o laspack/eigenval.c

errhandl.o: laspack/errhandl.c laspack/errhandl.h \
		laspack/copyrght.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o errhandl.o laspack/errhandl.c

factor.o: laspack/factor.c laspack/factor.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o factor.o laspack/factor.c

itersolv.o: laspack/itersolv.c laspack/itersolv.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o itersolv.o laspack/itersolv.c

matrix.o: laspack/matrix.c laspack/matrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o matrix.o laspack/matrix.c

mlsolv.o: laspack/mlsolv.c laspack/mlsolv.h \
		laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/matrix.h \
		laspack/qmatrix.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mlsolv.o laspack/mlsolv.c

operats.o: laspack/operats.c laspack/operats.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/vector.h \
		laspack/elcmp.h \
		laspack/matrix.h \
		laspack/qmatrix.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o operats.o laspack/operats.c

precond.o: laspack/precond.c laspack/precond.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/vector.h \
		laspack/elcmp.h \
		laspack/qmatrix.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h \
		laspack/factor.h \
		laspack/itersolv.h \
		laspack/eigenval.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o precond.o laspack/precond.c

qmatrix.o: laspack/qmatrix.c laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o qmatrix.o laspack/qmatrix.c

rtc.o: laspack/rtc.c laspack/rtc.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/vector.h \
		laspack/elcmp.h \
		laspack/itersolv.h \
		laspack/qmatrix.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/operats.h \
		laspack/matrix.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rtc.o laspack/rtc.c

vector.o: laspack/vector.c laspack/vector.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/errhandl.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o vector.o laspack/vector.c

shema.o: shema.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h \
		include/perem.c \
		include/viraj.c \
		include/nachal.c \
		include/mum.c \
		include/nodeparam.c \
		include/case0_L.c \
		include/case1_L.c \
		include/case2_L.c \
		include/case3_L.c \
		include/case4_L.c \
		include/case5_L.c \
		include/case6_L.c \
		include/case7_L.c \
		include/case0.c \
		include/case1.c \
		include/case2.c \
		include/case3.c \
		include/case4.c \
		include/case5.c \
		include/case6.c \
		include/case7.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o shema.o shema.c

solver.o: solver.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o solver.o solver.c

gnuplot.o: gnuplot.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gnuplot.o gnuplot.c

shema_s.o: shema_s.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h \
		include_S/perem.c \
		include_S/viraj.c \
		include_S/nachal.c \
		include_S/nodeparam_H.c \
		include_S/caseH.c \
		include_S/nodeparam_V.c \
		include_S/case0_L.c \
		include_S/case1_L.c \
		include_S/case2_L.c \
		include_S/case3_L.c \
		include_S/case4_L.c \
		include_S/case5_L.c \
		include_S/case6_L.c \
		include_S/case7_L.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o shema_s.o shema_s.c

setka_s.o: setka_s.c head.h \
		laspack/qmatrix.h \
		laspack/lastypes.h \
		laspack/copyrght.h \
		laspack/elcmp.h \
		laspack/vector.h \
		structs.h \
		laspack/itersolv.h \
		laspack/precond.h \
		laspack/eigenval.h \
		laspack/errhandl.h \
		laspack/rtc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o setka_s.o setka_s.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

